import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });
const sb = createClient(process.env.NEXT_PUBLIC_OMNISKILLS_SUPABASE_URL!, process.env.OMNISKILLS_SERVICE_KEY!);
const r = (a: number, b: number) => Math.floor(Math.random() * (b - a + 1)) + a;

const skills = [
  { name: "Docker Compose Patterns", slug: "gen2-docker-compose-patterns", tagline: "Multi-container orchestration with Docker Compose", description: "Define and run multi-container Docker applications with Compose files for development and production.", author: "Docker", url: "https://github.com/docker/compose", category: "devops", categories: ["devops", "automation"], keywords: ["docker", "compose", "containers", "orchestration"] },
  { name: "Docker Best Practices", slug: "gen2-docker-best-practices", tagline: "Optimize Docker images and containers for production", description: "Build efficient Docker images with multi-stage builds, layer caching, security scanning, and runtime optimization.", author: "Docker", url: "https://github.com/docker/docker-bench-security", category: "devops", categories: ["devops", "security"], keywords: ["docker", "best-practices", "optimization", "security"] },
  { name: "Kubernetes Operators", slug: "gen2-kubernetes-operators", tagline: "Extend Kubernetes with custom operators", description: "Build Kubernetes operators to automate complex application lifecycle management with custom controllers and CRDs.", author: "Kubernetes", url: "https://github.com/operator-framework/operator-sdk", category: "devops", categories: ["devops", "automation"], keywords: ["kubernetes", "operators", "crd", "controller"] },
  { name: "WebSocket Patterns", slug: "gen2-websocket-patterns", tagline: "Real-time bidirectional communication with WebSockets", description: "Implement WebSocket servers and clients for real-time chat, live updates, and multiplayer game communication.", author: "Community", url: "https://github.com/websockets/ws", category: "code-assistant", categories: ["code-assistant", "education"], keywords: ["websocket", "realtime", "bidirectional", "ws"] },
  { name: "GraphQL Apollo Patterns", slug: "gen2-graphql-apollo-patterns", tagline: "Build GraphQL APIs and clients with Apollo", description: "Implement GraphQL servers with Apollo Server and query data with Apollo Client for React and other frameworks.", author: "Apollo", url: "https://github.com/apollographql/apollo-server", category: "code-assistant", categories: ["code-assistant", "data-analysis"], keywords: ["graphql", "apollo", "server", "client"] },
  { name: "tRPC End-to-End Types", slug: "gen2-trpc-end-to-end", tagline: "End-to-end typesafe APIs with tRPC", description: "Build fully typesafe APIs without schemas or code generation using tRPC with TypeScript inference.", author: "Alex Johansson", url: "https://github.com/trpc/trpc", category: "code-assistant", categories: ["code-assistant", "devops"], keywords: ["trpc", "typescript", "typesafe", "rpc"] },
  { name: "Zod Schema Validation", slug: "gen2-zod-schema-validation", tagline: "TypeScript-first schema validation library", description: "Validate data with Zod schemas that provide static type inference, composable validators, and error formatting.", author: "Colin McDonnell", url: "https://github.com/colinhacks/zod", category: "code-assistant", categories: ["code-assistant", "education"], keywords: ["zod", "validation", "schema", "typescript"] },
  { name: "Turborepo Monorepo", slug: "gen2-turborepo-monorepo", tagline: "High-performance monorepo build system", description: "Manage monorepo builds with Turborepo intelligent caching, parallel execution, and task pipelines.", author: "Vercel", url: "https://github.com/vercel/turborepo", category: "devops", categories: ["devops", "code-assistant"], keywords: ["turborepo", "monorepo", "build", "caching"] },
  { name: "Nx Monorepo", slug: "gen2-nx-monorepo", tagline: "Smart monorepo tooling with computation caching", description: "Scale development with Nx workspace management, affected commands, distributed caching, and code generators.", author: "Nrwl", url: "https://github.com/nrwl/nx", category: "devops", categories: ["devops", "code-assistant"], keywords: ["nx", "monorepo", "workspace", "generators"] },
  { name: "Biome Formatter and Linter", slug: "gen2-biome-formatter", tagline: "Fast formatter and linter for web projects", description: "Format and lint JavaScript, TypeScript, JSX, and JSON with Biome single tool replacing Prettier and ESLint.", author: "Biome", url: "https://github.com/biomejs/biome", category: "code-assistant", categories: ["code-assistant", "devops"], keywords: ["biome", "formatter", "linter", "fast"] },
  { name: "ESLint Flat Config", slug: "gen2-eslint-flat-config", tagline: "Modern ESLint configuration with flat config", description: "Configure ESLint with the new flat config format for simpler, shareable, and composable linting rules.", author: "ESLint", url: "https://github.com/eslint/eslint", category: "code-assistant", categories: ["code-assistant", "education"], keywords: ["eslint", "flat-config", "linting", "javascript"] },
  { name: "Prettier Configuration", slug: "gen2-prettier-config", tagline: "Opinionated code formatter configuration", description: "Configure Prettier formatting rules for consistent code style across JavaScript, TypeScript, CSS, and Markdown.", author: "Prettier", url: "https://github.com/prettier/prettier", category: "code-assistant", categories: ["code-assistant", "writing"], keywords: ["prettier", "formatter", "code-style", "configuration"] },
  { name: "Bun Runtime", slug: "gen2-bun-runtime", tagline: "All-in-one JavaScript runtime and toolkit", description: "Run, build, test, and manage JavaScript projects with Bun fast all-in-one toolkit and npm-compatible runtime.", author: "Oven", url: "https://github.com/oven-sh/bun", category: "code-assistant", categories: ["code-assistant", "devops"], keywords: ["bun", "runtime", "fast", "bundler"] },
  { name: "Deno Deploy", slug: "gen2-deno-deploy", tagline: "Deploy TypeScript to the edge with Deno", description: "Deploy TypeScript and JavaScript applications globally with Deno Deploy edge runtime and KV storage.", author: "Deno", url: "https://github.com/denoland/deno", category: "devops", categories: ["devops", "code-assistant"], keywords: ["deno", "deploy", "edge", "typescript"] },
  { name: "Wrangler CLI", slug: "gen2-wrangler-cli", tagline: "Develop and deploy Cloudflare Workers locally", description: "Build and test Cloudflare Workers locally with Wrangler CLI for development, preview, and production deployment.", author: "Cloudflare", url: "https://github.com/cloudflare/workers-sdk", category: "devops", categories: ["devops", "code-assistant"], keywords: ["wrangler", "cloudflare", "workers", "cli"] },
  { name: "Hono Web Framework", slug: "gen2-hono-web-framework", tagline: "Ultrafast web framework for the edge", description: "Build web applications with Hono ultralight framework supporting Cloudflare Workers, Deno, Bun, and Node.js.", author: "Yusuke Wada", url: "https://github.com/honojs/hono", category: "code-assistant", categories: ["code-assistant", "devops"], keywords: ["hono", "edge", "ultrafast", "web"] },
  { name: "Elysia Framework", slug: "gen2-elysia-framework", tagline: "Ergonomic web framework for Bun runtime", description: "Build type-safe APIs with Elysia end-to-end type safety, Eden treaty client, and Bun-optimized performance.", author: "SaltyAom", url: "https://github.com/elysiajs/elysia", category: "code-assistant", categories: ["code-assistant", "devops"], keywords: ["elysia", "bun", "typesafe", "eden"] },
].map(s => ({ ...s, pricing_type: "free", install_count: r(2000, 15000), is_new: Math.random() < 0.15, is_trending: Math.random() < 0.1 }));

async function main() {
  const { data, error } = await sb.from("skills").upsert(skills, { onConflict: "slug" }).select("slug");
  if (error) console.error(error.message);
  else console.log("Inserted:", data.length);
  const { count } = await sb.from("skills").select("*", { count: "exact", head: true });
  console.log("Final total:", count);
}
main();
