import { createClient } from "@supabase/supabase-js"
import * as dotenv from "dotenv"

dotenv.config({ path: ".env.local" })

const supabase = createClient(
  process.env.NEXT_PUBLIC_OMNISKILLS_SUPABASE_URL!,
  process.env.OMNISKILLS_SERVICE_KEY!
)

const realSkills = [
  // === PART 1: CLAUDE SKILLS (Official Anthropic) ===
  // Document & Office
  { name: "PDF Processing", slug: "anthropic-pdf", tagline: "Read, extract tables, fill forms, merge/split PDFs", description: "Highest-utility skill for knowledge workers. Read, extract tables, fill forms, merge and split PDF documents with Claude.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/pdf", category: "productivity", categories: ["productivity", "automation"], keywords: ["PDF", "documents", "forms", "tables"], install_count: 185000 },
  { name: "DOCX Processing", slug: "anthropic-docx", tagline: "Create and edit Word docs with tracked changes, comments, formatting", description: "Full Word document manipulation with tracked changes, comments, formatting and more.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/docx", category: "productivity", categories: ["productivity", "writing"], keywords: ["Word", "DOCX", "documents", "formatting"], install_count: 142000 },
  { name: "PPTX Presentations", slug: "anthropic-pptx", tagline: "Slide decks from natural language with layouts, charts, speaker notes", description: "Create professional slide decks from natural language. Supports layouts, charts, and speaker notes.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/pptx", category: "productivity", categories: ["productivity", "design"], keywords: ["PowerPoint", "slides", "presentations", "charts"], install_count: 128000 },
  { name: "XLSX Spreadsheets", slug: "anthropic-xlsx", tagline: "Excel formulas, analysis, charts via plain English", description: "Manipulate Excel spreadsheets with formulas, data analysis, and chart creation through natural language.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/xlsx", category: "data-analysis", categories: ["data-analysis", "productivity"], keywords: ["Excel", "spreadsheets", "formulas", "charts"], install_count: 156000 },
  { name: "Doc Co-Authoring", slug: "anthropic-doc-coauthoring", tagline: "Real collaborative writing — human writes, Claude responds, back and forth", description: "True collaborative document authoring. Human writes sections, Claude responds and contributes, iterating together.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring", category: "writing", categories: ["writing", "productivity"], keywords: ["collaboration", "writing", "co-authoring"], install_count: 89000 },

  // Design & Creative
  { name: "Frontend Design", slug: "anthropic-frontend-design", tagline: "Escape AI slop aesthetics — real design systems, bold typography", description: "Create distinctive, production-grade frontend interfaces. Real design systems, bold typography. 277k+ installs.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/frontend-design", category: "design", categories: ["design", "code-assistant"], keywords: ["frontend", "design", "UI", "typography", "CSS"], install_count: 277000 },
  { name: "Canvas Design", slug: "anthropic-canvas-design", tagline: "Social graphics, posters, covers — text in, PNG/PDF out", description: "Create social media graphics, posters, and covers from text descriptions. Outputs PNG and PDF.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/canvas-design", category: "design", categories: ["design"], keywords: ["graphics", "social media", "posters", "PNG"], install_count: 95000 },
  { name: "Algorithmic Art", slug: "anthropic-algorithmic-art", tagline: "Fractal patterns, geometric compositions via p5.js", description: "Generate fractal patterns and geometric compositions using p5.js. Creative coding meets AI.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/algorithmic-art", category: "design", categories: ["design", "code-assistant"], keywords: ["art", "fractals", "p5.js", "creative coding"], install_count: 67000 },
  { name: "Theme Factory", slug: "anthropic-theme-factory", tagline: "Batch-generate color schemes from one prompt", description: "Generate multiple harmonious color schemes and themes from a single prompt. Perfect for design systems.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/theme-factory", category: "design", categories: ["design"], keywords: ["themes", "colors", "design system", "palette"], install_count: 54000 },
  { name: "Web Artifacts Builder", slug: "anthropic-web-artifacts", tagline: "Calculators, dashboards via natural language — no frontend skills needed", description: "Build interactive web artifacts like calculators and dashboards using natural language. No coding required.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder", category: "code-assistant", categories: ["code-assistant", "design"], keywords: ["web apps", "dashboards", "calculators", "no-code"], install_count: 112000 },

  // Dev & Engineering
  { name: "Superpowers", slug: "obra-superpowers", tagline: "20+ battle-tested skills — TDD, debugging, plan-to-execute pipeline", description: "Collection of 20+ battle-tested development skills including TDD, systematic debugging, and plan-to-execute pipelines. 96k+ stars on GitHub.", author: "obra", url: "https://github.com/obra/superpowers", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["TDD", "debugging", "development", "pipeline"], install_count: 96000 },
  { name: "Systematic Debugging", slug: "systematic-debugging", tagline: "Root cause analysis first, fix second — 4-phase methodology", description: "A systematic 4-phase debugging methodology: reproduce, isolate, identify root cause, then fix. Rated S9.2 on SkillHub.", author: "obra", url: "https://github.com/obra/superpowers", category: "code-assistant", categories: ["code-assistant"], keywords: ["debugging", "root cause", "methodology"], install_count: 78000 },
  { name: "File Search (Massgen)", slug: "massgen-file-search", tagline: "Ripgrep + ast-grep mastery for codebase navigation", description: "Master file search using ripgrep and ast-grep for efficient codebase navigation. Rated S9.0.", author: "massgen", url: "https://github.com/massgen/massgen", category: "code-assistant", categories: ["code-assistant"], keywords: ["search", "ripgrep", "ast-grep", "codebase"], install_count: 45000 },
  { name: "Context Optimization", slug: "context-optimization", tagline: "Reduce token costs and KV-cache tricks — 13.9k stars", description: "Agent skills for context engineering. Reduce token costs with KV-cache tricks and smart context management. 13.9k stars.", author: "muratcankoylan", url: "https://github.com/muratcankoylan/agent-skills-for-context-engineering", category: "code-assistant", categories: ["code-assistant", "productivity"], keywords: ["context", "tokens", "optimization", "KV-cache"], install_count: 62000 },
  { name: "Skill Creator", slug: "anthropic-skill-creator", tagline: "Meta-skill: describe a workflow, get a SKILL.md in 5 minutes", description: "The official meta-skill from Anthropic. Describe any workflow and get a complete SKILL.md file generated in 5 minutes.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/skill-creator", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["skill creation", "meta-skill", "workflow", "SKILL.md"], install_count: 134000 },
  { name: "Remotion Best Practices", slug: "remotion-best-practices", tagline: "AI video generation with React — 117k weekly installs", description: "Best practices for video creation with Remotion (React). Generate and edit videos programmatically.", author: "Remotion", url: "https://github.com/remotion-dev/remotion", category: "design", categories: ["design", "code-assistant"], keywords: ["video", "React", "Remotion", "animation"], install_count: 117000 },

  // Marketing & SEO
  { name: "Marketing Skills by Corey Haines", slug: "corey-haines-marketing", tagline: "20+ skills: CRO, copywriting, SEO, email sequences, growth", description: "Comprehensive marketing toolkit with 20+ skills covering CRO, copywriting, SEO, email sequences, and growth strategies.", author: "Corey Haines", url: "https://github.com/coreyhaines31/marketingskills", category: "writing", categories: ["writing", "automation"], keywords: ["marketing", "CRO", "SEO", "copywriting", "growth"], install_count: 43000 },
  { name: "Claude SEO", slug: "claude-seo", tagline: "Full-site audits, schema validation — 12 sub-skills", description: "Complete SEO toolkit with full-site audits, schema validation, and 12 specialized sub-skills for search optimization.", author: "AgriciDaniel", url: "https://github.com/AgriciDaniel/claude-seo", category: "research", categories: ["research", "writing"], keywords: ["SEO", "audit", "schema", "search optimization"], install_count: 38000 },
  { name: "Brand Guidelines", slug: "anthropic-brand-guidelines", tagline: "Encode your brand into a skill — auto-applies everywhere", description: "Encode your brand voice, style, and guidelines into a skill that automatically applies across all Claude interactions.", author: "Anthropic", url: "https://github.com/anthropics/skills/tree/main/skills/brand-guidelines", category: "writing", categories: ["writing", "productivity"], keywords: ["brand", "guidelines", "voice", "consistency"], install_count: 71000 },

  // Knowledge & Learning
  { name: "NotebookLM Integration", slug: "notebooklm-integration", tagline: "Claude + NotebookLM bridge — summaries, mind maps, flashcards", description: "Bridge between Claude and Google NotebookLM. Generate summaries, mind maps, and flashcards from your sources.", author: "PleasePrompto", url: "https://github.com/PleasePrompto/notebooklm-skill", category: "education", categories: ["education", "research"], keywords: ["NotebookLM", "summaries", "mind maps", "flashcards"], install_count: 29000 },
  { name: "Obsidian Skills", slug: "obsidian-skills", tagline: "By Obsidian's CEO — auto-tagging, auto-linking, vault-native", description: "Official Obsidian skills by the CEO. Auto-tagging, auto-linking, and vault-native operations for your knowledge base.", author: "kepano", url: "https://github.com/kepano/obsidian-skills", category: "productivity", categories: ["productivity", "automation"], keywords: ["Obsidian", "notes", "knowledge base", "tagging"], install_count: 52000 },
  { name: "Excel MCP Server", slug: "excel-mcp-server", tagline: "Manipulate Excel files without Microsoft Excel", description: "MCP server for Excel manipulation without needing Microsoft Excel installed. Full spreadsheet control.", author: "haris-musa", url: "https://github.com/haris-musa/excel-mcp-server", category: "data-analysis", categories: ["data-analysis", "automation"], keywords: ["Excel", "MCP", "spreadsheets"], install_count: 34000 },

  // === MCP SERVERS ===
  { name: "Tavily MCP", slug: "tavily-mcp", tagline: "Search engine built for AI agents — clean structured data, not blue links", description: "Search engine designed for AI agents. Returns clean structured data instead of blue links. Four tools: search, extract, crawl, map.", author: "Tavily", url: "https://github.com/tavily-ai/tavily-mcp", category: "research", categories: ["research", "automation"], keywords: ["search", "MCP", "web search", "AI agents"], install_count: 89000 },
  { name: "Context7", slug: "context7", tagline: "Injects up-to-date library docs into your LLM context — no hallucinated APIs", description: "Injects current library documentation into your LLM context. Supports Next.js, React, Supabase, MongoDB, and thousands more. Just add 'use context7' to your prompt.", author: "Upstash", url: "https://github.com/upstash/context7", category: "code-assistant", categories: ["code-assistant", "research"], keywords: ["documentation", "context", "MCP", "libraries"], install_count: 156000 },
  { name: "Task Master AI", slug: "task-master-ai", tagline: "Your AI's project manager — PRD to structured tasks with dependencies", description: "Feed a PRD, get structured tasks with dependencies. Claude executes them one by one. Works across Cursor, Claude Code, Windsurf.", author: "eyaltoledano", url: "https://github.com/eyaltoledano/claude-task-master", category: "productivity", categories: ["productivity", "automation"], keywords: ["project management", "tasks", "PRD", "dependencies"], install_count: 124000 },

  // === GITHUB REPOS — Agent Frameworks ===
  { name: "OpenClaw", slug: "openclaw", tagline: "Viral AI agent — persistent, multi-channel, writes its own skills", description: "The viral AI agent that's persistent, operates across multiple channels, and can write its own skills. 210k+ stars.", author: "OpenClaw", url: "https://github.com/openclaw/openclaw", category: "automation", categories: ["automation", "code-assistant"], keywords: ["agent", "autonomous", "multi-channel"], install_count: 210000 },
  { name: "AutoGPT", slug: "autogpt", tagline: "Full agent platform for long-running autonomous tasks", description: "Complete agent platform designed for long-running autonomous tasks. One of the original AI agent projects.", author: "Significant Gravitas", url: "https://github.com/Significant-Gravitas/AutoGPT", category: "automation", categories: ["automation", "code-assistant"], keywords: ["agent", "autonomous", "GPT", "automation"], install_count: 170000 },
  { name: "LangGraph", slug: "langgraph", tagline: "Agents as graphs — multi-agent orchestration — 26.8k stars", description: "Build agents as graphs with multi-agent orchestration. Part of the LangChain ecosystem. 26.8k stars.", author: "LangChain", url: "https://github.com/langchain-ai/langgraph", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["agents", "graphs", "orchestration", "LangChain"], install_count: 26800 },
  { name: "OWL Multi-Agent", slug: "owl-multi-agent", tagline: "Multi-agent cooperation — tops GAIA benchmark", description: "Multi-agent cooperation framework that tops the GAIA benchmark for AI agent performance.", author: "CAMEL-AI", url: "https://github.com/camel-ai/owl", category: "automation", categories: ["automation", "research"], keywords: ["multi-agent", "cooperation", "benchmark"], install_count: 18000 },
  { name: "Dify", slug: "dify-platform", tagline: "Open-source LLM app builder — workflows, RAG, agents all-in-one", description: "Open-source platform for building LLM applications. Includes workflows, RAG pipelines, and agents in one unified interface.", author: "LangGenius", url: "https://github.com/langgenius/dify", category: "automation", categories: ["automation", "code-assistant"], keywords: ["LLM", "platform", "RAG", "workflows"], install_count: 95000 },
  { name: "CrewAI", slug: "crewai", tagline: "Multi-agent framework with roles, goals, and backstories", description: "Build multi-agent systems where each agent has defined roles, goals, and backstories for realistic collaboration.", author: "CrewAI", url: "https://github.com/crewAIInc/crewAI", category: "automation", categories: ["automation", "code-assistant"], keywords: ["multi-agent", "roles", "collaboration"], install_count: 45000 },
  { name: "CopilotKit", slug: "copilotkit", tagline: "Embed AI copilots into React applications", description: "Framework for embedding AI copilots into React applications. In-app AI chat, AI-powered textareas, and more.", author: "CopilotKit", url: "https://github.com/CopilotKit/CopilotKit", category: "code-assistant", categories: ["code-assistant", "design"], keywords: ["React", "copilot", "AI", "chat"], install_count: 38000 },

  // Local AI
  { name: "Ollama", slug: "ollama", tagline: "Run LLMs locally with one command", description: "The simplest way to run large language models locally. One command setup, supports hundreds of models.", author: "Ollama", url: "https://github.com/ollama/ollama", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["local LLM", "inference", "self-hosted"], install_count: 320000 },
  { name: "Open WebUI", slug: "open-webui", tagline: "Self-hosted ChatGPT-like interface for any LLM", description: "Beautiful self-hosted ChatGPT-like interface. Works with Ollama, OpenAI, and any LLM backend.", author: "Open WebUI", url: "https://github.com/open-webui/open-webui", category: "code-assistant", categories: ["code-assistant", "productivity"], keywords: ["ChatGPT", "self-hosted", "UI", "LLM"], install_count: 280000 },
  { name: "LlamaFile", slug: "llamafile", tagline: "LLM as single executable — zero dependencies", description: "Package any LLM as a single executable file. Zero dependencies, runs on any platform.", author: "Mozilla", url: "https://github.com/Mozilla-Ocho/llamafile", category: "code-assistant", categories: ["code-assistant"], keywords: ["executable", "portable", "LLM", "Mozilla"], install_count: 45000 },
  { name: "Unsloth", slug: "unsloth", tagline: "Fine-tune LLMs 2x faster with 70% less memory", description: "Fine-tune large language models 2x faster while using 70% less memory. Supports LoRA and QLoRA.", author: "Unsloth", url: "https://github.com/unslothai/unsloth", category: "code-assistant", categories: ["code-assistant", "research"], keywords: ["fine-tuning", "LoRA", "optimization", "training"], install_count: 67000 },

  // Workflow & Automation
  { name: "n8n Automation", slug: "n8n-automation", tagline: "Open-source workflow automation with 400+ integrations + AI nodes", description: "Fair-code workflow automation with 400+ integrations and native AI nodes. Self-hosted alternative to Zapier.", author: "n8n", url: "https://github.com/n8n-io/n8n", category: "automation", categories: ["automation", "productivity"], keywords: ["automation", "workflows", "integrations", "no-code"], install_count: 98000 },
  { name: "Langflow", slug: "langflow", tagline: "Visual drag-and-drop for agent pipelines — 140k stars", description: "Visual framework for building multi-agent and RAG applications with drag-and-drop interface.", author: "Langflow", url: "https://github.com/langflow-ai/langflow", category: "automation", categories: ["automation", "code-assistant"], keywords: ["visual", "drag-and-drop", "RAG", "agents"], install_count: 140000 },
  { name: "Huginn", slug: "huginn", tagline: "Self-hosted web agents — monitoring, alerts, privacy-first", description: "Self-hosted system for building agents that monitor the web and take actions on your behalf. Privacy-first.", author: "Huginn", url: "https://github.com/huginn/huginn", category: "automation", categories: ["automation", "security"], keywords: ["monitoring", "alerts", "self-hosted", "privacy"], install_count: 43000 },

  // Search & Data
  { name: "GPT Researcher", slug: "gpt-researcher", tagline: "Autonomous research agent that compiles detailed reports", description: "Autonomous research agent that performs web research and compiles comprehensive reports on any topic.", author: "assafelovic", url: "https://github.com/assafelovic/gpt-researcher", category: "research", categories: ["research", "automation"], keywords: ["research", "reports", "autonomous", "web"], install_count: 56000 },
  { name: "Firecrawl", slug: "firecrawl", tagline: "Turn any website into LLM-ready structured data", description: "Crawl any website and convert it to clean, LLM-ready structured data. Perfect for RAG pipelines.", author: "Mendable", url: "https://github.com/mendableai/firecrawl", category: "data-analysis", categories: ["data-analysis", "automation"], keywords: ["scraping", "crawling", "data", "RAG"], install_count: 42000 },
  { name: "Vanna AI", slug: "vanna-ai", tagline: "Natural language to SQL — ask questions, get queries", description: "Ask questions in natural language and get accurate SQL queries. Works with any database.", author: "Vanna AI", url: "https://github.com/vanna-ai/vanna", category: "data-analysis", categories: ["data-analysis", "code-assistant"], keywords: ["SQL", "natural language", "database", "queries"], install_count: 34000 },

  // Dev Tools
  { name: "Codebase Memory MCP", slug: "codebase-memory-mcp", tagline: "Transform your codebase into a persistent knowledge graph", description: "MCP server that builds a persistent knowledge graph from your codebase. Never lose context across sessions.", author: "DeusData", url: "https://github.com/DeusData/codebase-memory-mcp", category: "code-assistant", categories: ["code-assistant", "productivity"], keywords: ["memory", "knowledge graph", "codebase", "MCP"], install_count: 28000 },
  { name: "DSPy", slug: "dspy-stanford", tagline: "Program (don't prompt) foundation models — Stanford NLP", description: "Programming framework for foundation models from Stanford NLP. Replace prompting with programming.", author: "Stanford NLP", url: "https://github.com/stanfordnlp/dspy", category: "code-assistant", categories: ["code-assistant", "research"], keywords: ["programming", "prompting", "Stanford", "framework"], install_count: 52000 },
  { name: "Spec Kit (GitHub)", slug: "spec-kit-github", tagline: "Spec-driven development — write specs, AI generates code — 50k+ stars", description: "Specification-driven development by GitHub. Write specifications, AI generates the implementation code.", author: "GitHub", url: "https://github.com/github/spec-kit", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["specifications", "code generation", "GitHub"], install_count: 50000 },

  // Curated Collections
  { name: "Awesome Claude Skills", slug: "awesome-claude-skills", tagline: "Best curated list of Claude skills — 22k+ stars", description: "The most comprehensive curated list of Claude Code skills and resources. 22k+ stars on GitHub.", author: "travisvn", url: "https://github.com/travisvn/awesome-claude-skills", category: "education", categories: ["education", "code-assistant"], keywords: ["awesome list", "curated", "skills", "resources"], install_count: 22000 },

  // === PART 3: Agent Orchestration & Multi-Agent ===
  { name: "gstack", slug: "gstack", tagline: "Claude Code as virtual engineering team", description: "Use Claude Code as a virtual engineering team. Orchestrate multiple AI agents for complex development tasks.", author: "Garry Tan", url: "https://github.com/garrytan/gstack", category: "automation", categories: ["automation", "code-assistant"], keywords: ["engineering team", "orchestration", "Claude Code"], install_count: 15000 },
  { name: "cmux", slug: "cmux", tagline: "Run multiple Claude agents in parallel sessions", description: "Multiplexer for Claude agents. Run multiple Claude instances in parallel for faster development.", author: "craigsc", url: "https://github.com/craigsc/cmux", category: "automation", categories: ["automation", "code-assistant"], keywords: ["parallel", "multiplexer", "agents"], install_count: 12000 },
  { name: "Figaro", slug: "figaro", tagline: "Orchestrate Claude agent fleets on desktop", description: "Desktop orchestrator for Claude agent fleets. Manage and coordinate multiple AI agents visually.", author: "byt3bl33d3r", url: "https://github.com/byt3bl33d3r/figaro", category: "automation", categories: ["automation", "code-assistant"], keywords: ["desktop", "orchestration", "fleet", "agents"], install_count: 8500 },
  { name: "Claude Squad", slug: "claude-squad", tagline: "Terminal agents running in parallel sessions", description: "Run Claude terminal agents in parallel sessions. Perfect for multi-task development workflows.", author: "smtg-ai", url: "https://github.com/smtg-ai/claude-squad", category: "automation", categories: ["automation", "code-assistant"], keywords: ["terminal", "parallel", "squad", "agents"], install_count: 18000 },
  { name: "Deer Flow (ByteDance)", slug: "deer-flow", tagline: "Sub-agents and sandboxes through skills — by ByteDance", description: "ByteDance's agent framework with sub-agents and sandboxed execution environments through skill definitions.", author: "ByteDance", url: "https://github.com/bytedance/deer-flow", category: "automation", categories: ["automation", "security"], keywords: ["ByteDance", "sub-agents", "sandbox", "skills"], install_count: 14000 },
  { name: "SWE-AF", slug: "swe-af", tagline: "One API call spins up a full engineering team", description: "Spin up a complete software engineering team with a single API call. Automated task decomposition and execution.", author: "Agent Field", url: "https://github.com/Agent-Field/SWE-AF", category: "automation", categories: ["automation", "code-assistant"], keywords: ["SWE", "engineering team", "API"], install_count: 9500 },
  { name: "AIlice", slug: "ailice", tagline: "Complex tasks decomposed into dynamic agent workflows", description: "Break complex tasks into dynamic agent workflows that execute autonomously.", author: "MyShell", url: "https://github.com/myshell-ai/AIlice", category: "automation", categories: ["automation"], keywords: ["dynamic agents", "task decomposition", "autonomous"], install_count: 7800 },
  { name: "Agent Alchemy", slug: "agent-alchemy", tagline: "Claude Code + plugins + task manager combined", description: "Combines Claude Code with a plugin system and task manager for enhanced agent capabilities.", author: "sequenzia", url: "https://github.com/sequenzia/agent-alchemy", category: "automation", categories: ["automation", "code-assistant"], keywords: ["plugins", "task manager", "Claude Code"], install_count: 6200 },

  // Agent Infrastructure & Security
  { name: "Ghost OS", slug: "ghost-os", tagline: "AI agents that operate every Mac app natively", description: "Operating system layer that lets AI agents control and operate any Mac application natively.", author: "Ghostwright", url: "https://github.com/ghostwright/ghost-os", category: "automation", categories: ["automation", "productivity"], keywords: ["Mac", "OS", "native apps", "control"], install_count: 11000 },
  { name: "e2b Desktop", slug: "e2b-desktop", tagline: "Isolated virtual desktops for AI agents", description: "Spin up isolated virtual desktop environments for AI agents. Safe sandboxed execution.", author: "E2B", url: "https://github.com/e2b-dev/desktop", category: "security", categories: ["security", "automation"], keywords: ["virtual desktop", "sandbox", "isolation", "agents"], install_count: 16000 },
  { name: "Container Use (Dagger)", slug: "container-use-dagger", tagline: "Containerized environments for coding agents", description: "Dagger-powered containerized environments specifically designed for AI coding agents.", author: "Dagger", url: "https://github.com/dagger/container-use", category: "devops", categories: ["devops", "security"], keywords: ["containers", "Dagger", "sandbox", "agents"], install_count: 13000 },
  { name: "Canopy P2P", slug: "canopy-p2p", tagline: "Encrypted P2P mesh network for AI agents", description: "Encrypted peer-to-peer mesh network enabling secure communication between AI agents.", author: "kwalus", url: "https://github.com/kwalus/Canopy", category: "security", categories: ["security", "automation"], keywords: ["P2P", "encryption", "mesh", "agents"], install_count: 5400 },
  { name: "Agent Governance Toolkit", slug: "agent-governance-microsoft", tagline: "Security middleware for AI agents — by Microsoft", description: "Microsoft's security middleware for governing AI agent behavior. Policy enforcement and monitoring.", author: "Microsoft", url: "https://github.com/microsoft/agent-governance-toolkit", category: "security", categories: ["security", "automation"], keywords: ["governance", "security", "Microsoft", "policy"], install_count: 9200 },
  { name: "Claude Code Security Review", slug: "claude-code-security-review", tagline: "Automated PR security analysis — by Anthropic", description: "Anthropic's official tool for automated security analysis of pull requests using Claude.", author: "Anthropic", url: "https://github.com/anthropics/claude-code-security-review", category: "security", categories: ["security", "code-assistant"], keywords: ["security review", "PRs", "Anthropic", "analysis"], install_count: 21000 },
  { name: "Promptfoo", slug: "promptfoo", tagline: "Automated security testing for AI models", description: "Test AI models for security vulnerabilities, prompt injection, and other risks automatically.", author: "Promptfoo", url: "https://github.com/promptfoo/promptfoo", category: "security", categories: ["security", "code-assistant"], keywords: ["testing", "security", "prompt injection", "evaluation"], install_count: 32000 },

  // Memory & Context
  { name: "Mem9", slug: "mem9", tagline: "Persistent memory system for AI agents", description: "Give AI agents persistent memory across sessions. Remember context, preferences, and past interactions.", author: "Mem9 AI", url: "https://github.com/mem9-ai/mem9", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["memory", "persistent", "context", "agents"], install_count: 8900 },
  { name: "Codefire", slug: "codefire", tagline: "Persistent memory specifically for coding agents", description: "Persistent memory system designed specifically for coding agents. Remember codebase context across sessions.", author: "WebsiteButlers", url: "https://github.com/websitebutlers/codefire-app", category: "code-assistant", categories: ["code-assistant"], keywords: ["memory", "coding", "persistent", "context"], install_count: 6700 },
  { name: "Memobase", slug: "memobase", tagline: "User profile memory for LLMs", description: "Build user profile memories for LLMs. Personalize AI interactions based on accumulated user knowledge.", author: "MemoDB", url: "https://github.com/memodb-io/memobase", category: "code-assistant", categories: ["code-assistant", "productivity"], keywords: ["memory", "user profiles", "personalization"], install_count: 5200 },

  // Coding Agents & Dev Tools
  { name: "Qwen Code", slug: "qwen-code", tagline: "Terminal AI coding agent by QwenLM (Alibaba)", description: "Terminal-based AI coding agent from Alibaba's QwenLM team. Code generation and editing in your terminal.", author: "QwenLM", url: "https://github.com/QwenLM/qwen-code", category: "code-assistant", categories: ["code-assistant"], keywords: ["terminal", "coding", "Qwen", "Alibaba"], install_count: 23000 },
  { name: "gptme", slug: "gptme", tagline: "Personal AI agent living in your terminal", description: "Your personal AI agent that lives in the terminal. Execute code, manage files, browse the web.", author: "gptme", url: "https://github.com/gptme/gptme", category: "code-assistant", categories: ["code-assistant", "productivity"], keywords: ["terminal", "personal agent", "CLI"], install_count: 15000 },
  { name: "Claude Inspector", slug: "claude-inspector", tagline: "See the hidden Claude Code prompt mechanics", description: "Inspect and understand the hidden prompt mechanics behind Claude Code's behavior.", author: "kangraemin", url: "https://github.com/kangraemin/claude-inspector", category: "code-assistant", categories: ["code-assistant", "education"], keywords: ["inspector", "prompts", "mechanics", "debugging"], install_count: 11000 },
  { name: "TDD Guard", slug: "tdd-guard", tagline: "Enforce test-first development for AI agents", description: "Ensures AI coding agents follow test-driven development. Tests first, implementation second.", author: "nizos", url: "https://github.com/nizos/tdd-guard", category: "code-assistant", categories: ["code-assistant", "security"], keywords: ["TDD", "testing", "guard", "enforcement"], install_count: 7500 },
  { name: "rendergit (Karpathy)", slug: "rendergit-karpathy", tagline: "Git repo rendered as single file for humans and LLMs", description: "Andrej Karpathy's tool to render an entire Git repository as a single file optimized for human and LLM reading.", author: "Andrej Karpathy", url: "https://github.com/karpathy/rendergit", category: "code-assistant", categories: ["code-assistant", "productivity"], keywords: ["git", "rendering", "Karpathy", "context"], install_count: 34000 },
  { name: "autoresearch (Karpathy)", slug: "autoresearch-karpathy", tagline: "Autonomous LLM training system by Karpathy", description: "Andrej Karpathy's autonomous system for LLM training research and experimentation.", author: "Andrej Karpathy", url: "https://github.com/karpathy/autoresearch", category: "research", categories: ["research", "code-assistant"], keywords: ["training", "LLM", "Karpathy", "autonomous"], install_count: 28000 },
  { name: "Pydantic AI", slug: "pydantic-ai", tagline: "Type-safe AI agent framework with Pydantic validation", description: "Build type-safe AI agents with Pydantic validation. Structured outputs and robust error handling.", author: "Pydantic", url: "https://github.com/pydantic/pydantic-ai", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["Pydantic", "type-safe", "validation", "agents"], install_count: 41000 },
  { name: "Claude Deep Research", slug: "claude-deep-research", tagline: "8-phase research skill with auto-continuation", description: "Comprehensive 8-phase research methodology with automatic continuation. Deep dive into any topic.", author: "199 Biotechnologies", url: "https://github.com/199-biotechnologies/claude-deep-research-skill", category: "research", categories: ["research", "education"], keywords: ["deep research", "methodology", "auto-continuation"], install_count: 19000 },

  // MCP & Integrations
  { name: "MCP Playwright", slug: "mcp-playwright", tagline: "Browser automation for LLMs via MCP", description: "MCP server enabling LLMs to control browsers via Playwright. Automated testing and web interaction.", author: "ExecuteAutomation", url: "https://github.com/executeautomation/mcp-playwright", category: "automation", categories: ["automation", "code-assistant"], keywords: ["Playwright", "browser", "automation", "MCP"], install_count: 27000 },
  { name: "Stealth Browser MCP", slug: "stealth-browser-mcp", tagline: "Undetectable browser automation for AI agents", description: "Stealth browser automation that avoids bot detection. For legitimate scraping and testing use cases.", author: "vibheksoni", url: "https://github.com/vibheksoni/stealth-browser-mcp", category: "automation", categories: ["automation", "security"], keywords: ["stealth", "browser", "undetectable", "scraping"], install_count: 16000 },
  { name: "FastMCP", slug: "fastmcp", tagline: "Build MCP servers in minimal Python code", description: "The fastest way to build MCP servers. Minimal Python code, maximum functionality.", author: "jlowin", url: "https://github.com/jlowin/fastmcp", category: "code-assistant", categories: ["code-assistant", "automation"], keywords: ["MCP", "Python", "server", "framework"], install_count: 35000 },
  { name: "Markdownify MCP", slug: "markdownify-mcp", tagline: "Convert PDFs, images, audio to Markdown via MCP", description: "MCP server that converts PDFs, images, and audio files into clean Markdown format.", author: "zcaceres", url: "https://github.com/zcaceres/markdownify-mcp", category: "productivity", categories: ["productivity", "automation"], keywords: ["Markdown", "conversion", "PDF", "MCP"], install_count: 22000 },
  { name: "MCPHub", slug: "mcphub", tagline: "Manage multiple MCP servers via HTTP gateway", description: "Central HTTP gateway for managing multiple MCP servers. Unified access point for all your MCP tools.", author: "samanhappy", url: "https://github.com/samanhappy/mcphub", category: "devops", categories: ["devops", "automation"], keywords: ["MCPHub", "gateway", "management", "HTTP"], install_count: 14000 },

  // Search, Data & LLM Tools
  { name: "CK Semantic Search", slug: "ck-semantic-search", tagline: "Search code by meaning, not just keywords", description: "Semantic code search that understands meaning. Find code by what it does, not just what it's named.", author: "BeaconBay", url: "https://github.com/BeaconBay/ck", category: "code-assistant", categories: ["code-assistant", "research"], keywords: ["semantic search", "code search", "meaning"], install_count: 8700 },
  { name: "ExtractThinker", slug: "extractthinker", tagline: "ORM for document intelligence and extraction", description: "Object-relational mapping approach to document intelligence. Extract structured data from any document.", author: "enoch3712", url: "https://github.com/enoch3712/ExtractThinker", category: "data-analysis", categories: ["data-analysis", "automation"], keywords: ["document intelligence", "extraction", "ORM"], install_count: 11000 },
  { name: "OmniRoute", slug: "omniroute", tagline: "API proxy for 44+ AI providers in one endpoint", description: "Unified API proxy supporting 44+ AI providers. One endpoint to rule them all.", author: "diegosouzapw", url: "https://github.com/diegosouzapw/OmniRoute", category: "devops", categories: ["devops", "code-assistant"], keywords: ["API proxy", "multi-provider", "routing"], install_count: 7500 },
  { name: "dlt Data Pipelines", slug: "dlt-pipelines", tagline: "LLM-native data pipelines from 5,000+ sources", description: "Data load tool with native LLM support. Build data pipelines from 5,000+ sources with Python.", author: "dlt-hub", url: "https://github.com/dlt-hub/dlt", category: "data-analysis", categories: ["data-analysis", "automation"], keywords: ["data pipelines", "ETL", "LLM", "Python"], install_count: 19000 },
  { name: "simonw/llm CLI", slug: "simonw-llm", tagline: "Lightweight CLI for local and remote LLMs", description: "Simon Willison's lightweight command-line tool for interacting with local and remote LLMs.", author: "Simon Willison", url: "https://github.com/simonw/llm", category: "code-assistant", categories: ["code-assistant", "productivity"], keywords: ["CLI", "LLM", "lightweight", "terminal"], install_count: 25000 },
  { name: "Portkey Gateway", slug: "portkey-gateway", tagline: "Route requests to 250+ LLMs with one API", description: "AI gateway that routes requests to 250+ LLMs. Load balancing, fallbacks, and caching built in.", author: "Portkey AI", url: "https://github.com/Portkey-AI/gateway", category: "devops", categories: ["devops", "code-assistant"], keywords: ["gateway", "routing", "LLM", "API"], install_count: 31000 },
  { name: "Laminar (lmnr)", slug: "laminar-lmnr", tagline: "Trace and evaluate AI agent behavior", description: "Observability platform for AI agents. Trace executions, evaluate outputs, and monitor performance.", author: "lmnr-ai", url: "https://github.com/lmnr-ai/lmnr", category: "code-assistant", categories: ["code-assistant", "devops"], keywords: ["tracing", "evaluation", "observability", "agents"], install_count: 13000 },

  // Video & More
  { name: "LTX Desktop (Lightricks)", slug: "ltx-desktop", tagline: "Generate and edit videos locally — by Lightricks", description: "Desktop application for local video generation and editing using AI. By Lightricks.", author: "Lightricks", url: "https://github.com/Lightricks/LTX-Desktop", category: "design", categories: ["design", "automation"], keywords: ["video", "generation", "editing", "local"], install_count: 17000 },
  { name: "MetaClaw", slug: "metaclaw", tagline: "Evolve AI agents without needing a GPU", description: "Evolutionary approach to AI agent development that doesn't require GPU resources.", author: "Aiming Lab", url: "https://github.com/aiming-lab/MetaClaw", category: "research", categories: ["research", "code-assistant"], keywords: ["evolution", "agents", "no-GPU", "optimization"], install_count: 6800 },
  { name: "Vane AI", slug: "vane-ai", tagline: "AI answering engine powered by local LLMs", description: "Build your own AI answering engine using local LLMs. Privacy-first search and answers.", author: "ItzCrazyKns", url: "https://github.com/ItzCrazyKns/Vane", category: "research", categories: ["research", "automation"], keywords: ["search engine", "local LLM", "answering", "privacy"], install_count: 9400 },
]

async function importReal() {
  console.log(`Importing ${realSkills.length} real skills/tools...`)

  const batchSize = 50
  let inserted = 0
  let errors = 0

  for (let i = 0; i < realSkills.length; i += batchSize) {
    const batch = realSkills.slice(i, i + batchSize).map(s => ({
      ...s,
      pricing_type: "free",
      is_new: false,
      is_trending: s.install_count > 50000,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }))

    const { error } = await supabase.from("skills").upsert(batch, { onConflict: "slug" })
    if (error) {
      console.error(`Batch error:`, error.message)
      errors += batch.length
    } else {
      inserted += batch.length
    }
    process.stdout.write(`\r  Progress: ${inserted + errors}/${realSkills.length}`)
  }

  console.log(`\n\nDone! Inserted: ${inserted}, Errors: ${errors}`)

  // Update category counts
  const { data: cats } = await supabase.from("categories").select("slug")
  if (cats) {
    for (const cat of cats) {
      const { count } = await supabase.from("skills").select("*", { count: "exact", head: true }).contains("categories", [cat.slug])
      await supabase.from("categories").update({ skill_count: count || 0 }).eq("slug", cat.slug)
    }
    console.log("Category counts updated!")
  }
}

importReal().catch(console.error)
